# Generated by Django 5.1.4 on 2024-12-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_desc', models.TextField(max_length=200)),
                ('movie_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
