# Generated by Django 5.1.4 on 2024-12-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.TextField(choices=[('ACTION', 'ACTION'), ('THRILLER', 'THRILLER'), ('ROMANCE', 'ROMANCE'), ('COMIC', 'COMIC'), ('CLASSIC', 'CLASSIC'), ('DRAMA', 'DRAMA')], null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.DateField(null=True),
        ),
    ]
