# Generated by Django 5.1.4 on 2024-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_small_desc_alter_movie_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_writers',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
