# Generated by Django 5.1.4 on 2024-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movie_director_movie_movie_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_runtime',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
